### ISSUE TITLE
Have you tested this against other optimization algorithms for standard benchmark datasets?

### ISSUE THREAD

**Issue by sgbaird** [ZebinYang/seqmml#2]
See e.g.
> Eriksson, D.; Jankowiak, M. High-Dimensional Bayesian Optimization with Sparse Axis-Aligned Subspaces. arXiv:2103.00349 [cs, stat] 2021.

**Comment by ZebinYang** [comment]
Hi, thanks for your question. We made comparisons against classic BO methods and non-sequential methods; the details can be found in our paper "Hyperparameter Optimization via Sequential Uniform Designs".
