### ISSUE TITLE
Quasi-Monte Carlo sampling

### ISSUE THREAD

**Issue by candalfigomoro** [ZebinYang/seqmml#4]
Could Quasi-Monte Carlo sampling (e.g. Sobol sequence https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.Sobol.html) provide a better exploration/coverage of the search space than uniform sampling?

**Comment by ZebinYang** [comment]
@candalfigomoro 

In general, uniform design (UD) is better than the Sobol sequence in terms of the coverage of search space, as UD is obtained by optimizing certain uniformity criteria. You may find more details in our paper http://jmlr.org/papers/v22/20-058.html.
